### ISSUE TITLE
Projektplan

### ISSUE THREAD

**Issue by hannsen** [hannsen/Rechnermodul#10]
einschließlich Personaleinsatz fürs Gesamtprojekt, als MS Project Datei, Version 2013

**20 Punkte**

**Comment by coolbc2000** [comment]
Wird ich machen. Aber naja mal schauen ;)

**Comment by hannsen** [comment]
Hör auf die issues zu schließen

**Comment by coolbc2000** [comment]
Diggah warum. Es ist doch fertig.

**Comment by hannsen** [comment]
Weil es in der 3, Woche abgegeben werden soll und das keiner von uns gesehen hat denke ich mal

**Comment by coolbc2000** [comment]
Ich geb zu, das sollen wir an der 3. woche abgeben. Ich hab das aber Jan und Karsten gezeigt und sogar ausgedruckt und die fanden das ganz gut. Also naja. Du kannst es auch selber angucken?
