### ISSUE TITLE
Design Klassendiagramm im Pflichtenheft

### ISSUE THREAD

**Issue by hannsen** [hannsen/Rechnermodul#12]
**+x Punkte**

**Comment by coolbc2000** [comment]
Schriftlich oder Programm?

**Comment by hannsen** [comment]
Denke mal mit MS Project

**Comment by coolbc2000** [comment]
Gut, muss ich also MS Project eher lernen. Wird ich evtl. machen.

**Comment by hannsen** [comment]
müssen wir nicht machen
