### ISSUE TITLE
Prototyping der GUI

### ISSUE THREAD

**Issue by hannsen** [hannsen/Rechnermodul#14]
anlässlich Meilensteinberatung mit dem Kunden 

- [ ] Prototyp:  **mind. 15 Punkte**
- [ ] Beratung : **12 Punkte**
- [ ] Protokoll : **8 Punkte**

**Comment by coolbc2000** [comment]
Wann/Habt ihr schon angefangen?

Wollt ihr das beim Arbeit erledigen?

**Comment by kalehmann** [comment]
GUI-Prototyp 12/15 Punkten
Beratung: 10/12 Punkten
