### ISSUE TITLE
Projektantrag mit rückseitiger Begründung

### ISSUE THREAD

**Issue by hannsen** [hannsen/Rechnermodul#2]
1. Woche **10 Punkte**

**Comment by kalehmann** [comment]
**Projektbezeichnung:**
Rechnermodul "JustForYou"

**Comment by kalehmann** [comment]
**Auftraggeber:**
Kleinstweich Deutschland GmbH (KWD)

**Comment by kalehmann** [comment]
**Terminziel:**
Fertigstellung bis 06/2018

**Comment by kalehmann** [comment]
**Kostenziel:**
30.000,00 €

**Comment by kalehmann** [comment]
**Nichtziele:**
- Kompatibilität mit anderen Betriebssystemen außer Microsoft Windows
- Nachbesserungen oder Updates
- Internationalisation
- Optimierung für Touch-Eingaben
- Protokollierung von Fehleingaben und/oder Rechnungsabbrüchen
- Bereitstellung passender Hardware

**Comment by kalehmann** [comment]
**Hauptaufgaben:**
- Implementierung der im Lastenheft genannten Module
- Kompatibilität mit Microsoft Windows
- Bedienung allein mit der Maus möglich
- Ui Konfigurierbar

**Comment by kalehmann** [comment]
**Schnittstelle zu anderen Prohjekten:**
- proprietäre dlls

**Comment by femmrich** [comment]
Daten aus den Comments sollten in Datei übernommen werden

**Comment by kalehmann** [comment]
Alles was momentan bei den Leistungszielen steht gehört eigentlich zu den Hauptaufgaben

**Comment by kalehmann** [comment]
Review Release Candidate @hannsen @femmrich @RiJonathan @coolbc2000

**Comment by femmrich** [comment]
Soll bei Ersteller nich ne Unterschrift rein?

**Comment by kalehmann** [comment]
kp

**Comment by femmrich** [comment]
sehr jut

**Comment by femmrich** [comment]
mach aber mal nur einen namen rein

**Comment by femmrich** [comment]
un bei kopie an noch nen anprechpartner (Dammmüller vermutlich)

**Comment by kalehmann** [comment]
Projektantrag abgesendet
