### ISSUE TITLE
Fehler in der Prozentsatzfunktion

### ISSUE THREAD

**Issue by kalehmann** [hannsen/Rechnermodul#20]
Die Rechnung in der Prozentsatz Funktion des Prozentrechnungsmodules ist Fehlerhaft. 100 und grundwert müssen vertauscht werden.

**Comment by coolbc2000** [comment]
@Jan Fertig?

**Comment by hannsen** [comment]
ja deine mudda hat das schon fertig gemacht

**Comment by jan** [comment]
Hat euch eure Mudda denn nicht beigebracht, keine fremden Männer zu taggen?

**Comment by hannsen** [comment]
Sorry, der @coolbc2000 is n bissel dumm

**Comment by kalehmann** [comment]
:rofl:
