### ISSUE TITLE
Projektstrukturplan in Bauplanansicht

### ISSUE THREAD

**Issue by hannsen** [hannsen/Rechnermodul#3]
2. Woche **15 Punkte**

**Comment by coolbc2000** [comment]
https://projekte-leicht-gemacht.de/blog/pm-methoden-erklaert/der-projektstrukturplan-teil-1-nutzen-aufbau-vorlage/

**Comment by femmrich** [comment]
Absprache bezüglich Zeiten für einzelne Module / Schritte (vllt. individuell gestaltet)

**Comment by femmrich** [comment]
Review, ansonsten fertig

**Comment by kalehmann** [comment]
Sieht eigentlich gut aus

**Comment by hannsen** [comment]
Hat denn jetzt schon jemand von euch das abgeschickt?

**Comment by kalehmann** [comment]
Ja, ich habe alles am Donnerstag abgeschickt
